tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "robotsandpencils/made"

brew "aria2"
brew "asdf"
brew "starship"
brew "swiftformat"
brew "swiftlint"
brew "xcbeautify"
brew "robotsandpencils/made/xcodes"

cask "copilot-for-xcode"
cask "font-jetbrains-mono-nerd-font"
cask "swiftformat-for-xcode"
cask "warp"